{
 "title": "Port Forwarding Agents",
 "tags": [
  "port-forwarding",
  "pfa"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Port Forwarding Agents Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Agents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=~\"web-port-forwarding-agent-.+\"})",
     "legendFormat": "# of Agents"
    }
   ]
  },
  {
   "title": "Agents - Not Connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"web-port-forwarding-agent\"}",
     "legendFormat": "# of available Agents"
    }
   ]
  },
  {
   "title": "Agents - Unavailable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"web-port-forwarding-agent\"}",
     "legendFormat": "# of Pending Agents"
    }
   ]
  }
 ]
}