# dockerfile for VsClk.Portal.WebSite
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2-alpine3.10
LABEL maintainer="johnri@microsoft.com"
ARG source
WORKDIR /app
COPY ${source:-.} .

# Debug Stuff
RUN apk add --no-cache procps
RUN wget https://aka.ms/getvsdbgsh -O - 2>/dev/null | /bin/sh /dev/stdin -v latest -l /vsdbg

ENTRYPOINT ["dotnet", "Microsoft.VsCloudKernel.Services.VsClk.Portal.WebSite.dll"]
