apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nginx-ingress-controller-clusterrole
rules:
  - apiGroups:
    - ""
    resources:
    - "nodes"
    verbs:
    - "get"
    - "list"
