# Default values for char vsclk-signalservice
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pods:
  replicaCount: 1
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath: /health
  readinessProbePath: /warmup
  targetCpuUtilizationPercentage: 80
  autoscaling: false

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.signalservice
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: signalservice
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  path: /api/signalr/?(.*)

appSettings:
- ASPNETCORE_ENVIRONMENT
- AppSettings__Stamp
- AppSettings__BaseUri
- AppSettings__ImageTag
- AppSettings__AuthenticateProfileServiceUri
- AppSettings__AzureCosmosDbEndpointUrl
- AppSettings__AzureCosmosDbAuthKey
- Azure__SignalR__ConnectionString

# override this value when another base Uri is used to connect to this app
baseUri: https://signlr.dev.core.vsengsaas.visualstudio.com/api/signalr

authentication:
# this is the default auth Profile service Uri the container will use for auth 
  authenticateProfileServiceUri: https://insiders.liveshare.vsengsaas.visualstudio.com/api/v1.2/profile

#define the stamp
stamp: use