# Default values for char vsclk-signalservice
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pods:
  replicaCount: 1
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath:
  readinessProbePath:
  targetCpuUtilizationPercentage: 60

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.signalservice
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: signalservice
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
  path: /api/signalr/?(.*)

appSettings:
- ASPNETCORE_ENVIRONMENT
- SIGNALR_AppSettings__AuthenticateMetadataServiceUri
- SIGNALR_AppSettings__AzureCosmosDbAuthKey
- SIGNALR_AppSettings__AzureCosmosDbEndpointUrl
- SIGNALR_AppSettings__AzureSignalRConnectionString
- SIGNALR_AppSettings__BuildVersion
- SIGNALR_AppSettings__GitCommit
- AppSettings__BuildVersion
- AppSettings__GitCommit
- AppSettings__AuthenticateMetadataServiceUri
- AppSettings__AzureCosmosDbEndpointUrl
- AppSettings__AzureCosmosDbAuthKey
- Azure__SignalR__ConnectionString

azure-secrets:
  # vsclk-core-dev
  subscriptionId-dev: "86642df6-843e-4610-a956-fdd497102261"
  # vsclk-core-ppe
  subscriptionId-ppe: "a3c9bfe3-6696-4b72-a51a-48d3f6e69a24"
  # vsclk-core-prod
  subscriptionId-prod: "979523fb-a19c-4bb0-a8ee-cef29597b0a4"
  keyVaultName-dev: vsclk-online-dev-kv
  keyVaultName-ppe: vsclk-online-ppe-kv
  keyVaultName-prod: vsclk-online-prod-kv

authentication:
  authority: https://login.windows.net/common
  # Note that 9db1d849-f699-4cfb-8160-64bed3335c72 is the DEV appid
  # the others are temporary, client appids
  audiences: "https://management.core.windows.net/,9db1d849-f699-4cfb-8160-64bed3335c72,aebc6443-996d-45c2-90f0-388ff96faa56,872cd9fa-d31f-45e0-9eab-6e460a02d1f1"

authentication:
 # this is the default auth Uri the container will use for auth 
  authenticateMetadataServiceUri: https://prod.liveshare.vsengsaas.visualstudio.com/api/authenticatemetadata

status:
  buildVersion: '1.0'
  gitCommit: unknown
