# Default values for char vsclk-signalservice
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pods:
  replicaCount: 1
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath:
  readinessProbePath:
  targetCpuUtilizationPercentage: 60

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.signalservice
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: signalservice
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  path: /api/signalr/?(.*)

appSettings:
- ASPNETCORE_ENVIRONMENT
- AppSettings__Stamp
- AppSettings__BaseUri
- AppSettings__ImageTag
- AppSettings__AuthenticateMetadataServiceUri
- AppSettings__AzureCosmosDbEndpointUrl
- AppSettings__AzureCosmosDbAuthKey
- Azure__SignalR__ConnectionString

# override this value when another base Uri is used to connect to this app
baseUri: https://signlr.dev.core.vsengsaas.visualstudio.com/api/signalr

authentication:
  authority: https://login.windows.net/common
# this is the default auth Uri the container will use for auth 
  authenticateMetadataServiceUri: https://prod.liveshare.vsengsaas.visualstudio.com/api/authenticatemetadata

#define the stamp
stamp: use