# Default values for char vsclk-signalservice
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pods:
  replicaCount: 3
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath: /health
  readinessProbePath: /warmup
  targetCpuUtilizationPercentage: 80
  autoscaling: false

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.signalservice
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: signalservice
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  path: /api/signalr/?(.*)

appSettings:
- ASPNETCORE_ENVIRONMENT
- AppSettings__Stamp
- AppSettings__BaseUri
- AppSettings__ImageTag
- AppSettings__AuthenticateProfileServiceUri
- AppSettings__KeyVaultName
- AppSettings__SubscriptionId
- AppSettings__ResourceGroupName
- AppSettings__ResourceGroupInstanceName
- AppSettings__AzureCacheRedisName
- AppSettings__AzureCosmosDbName
- ApplicationServicePrincipal__ClientId
- ApplicationServicePrincipal__TenantId
- ApplicationServicePrincipal__ClientPassword


# override this value when another base Uri is used to connect to this app
baseUri: https://signlr.dev.core.vsengsaas.visualstudio.com/api/signalr

authentication:
# this is the default auth Profile service Uri the container will use for auth 
  authenticateProfileServiceUri: https://insiders.liveshare.vsengsaas.visualstudio.com/api/v1.2/profile

#define the stamp (this will be overridden by the release definition for each stamp/location)
stamp: usw2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  requests:
  #  cpu: 250m
  #  limits:
  #  cpu: 500m
  #requests:
  #  memory: 3000Mi
  #limits:
  #  memory: 4000Mi
