apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-configmap
  labels:
    k8s-app: nginx-ingress-controller
    {{ template "labelvalues" . }}
data:
  add-headers: {{ .Release.Namespace }}/nginx-ingress-controller-add-headers
  client-header-buffer-size: "1M"
  client-max-body-size: "2M"
  forwarded-for-header: "true"
  generate-request-id: "true"
  hsts-include-subdomains: "true"
  hsts-max-age: "31536000"
  hsts: "true"
  proxy-add-original-uri-header: "true"
  proxy-buffer-size: "1M"
  proxy-connect-timeout: "300"
  proxy-read-timeout: "300"
  proxy-request-buffering: "off"
  proxy-send-timeout: "300"
  proxy-set-headers: {{ .Release.Namespace }}/nginx-ingress-controller-proxy-set-headers
  send-timeout: "300"
  ssl-ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256"
  ssl-session-tickets: "false"
  ssl-session-timeout: "10m"
  upstream-keepalive-timeout: "300"
  use-forwarded-headers: "true"
  log-format-upstream: '{"time":"$time_iso8601","XRequestId":"$req_id","BytesSent":"$bytes_sent","HttpResponseDuration":"$request_time","HttpResponseStatus":"$status","HttpRequestHost":"$host","HttpRequestProtocol":"$server_protocol","HttpRequestUri":"$uri","HttpRequestQuery":"$args","HttpRequestLength":"$request_length","HttpRequestMethod":"$request_method","HttpRequestReferrer":"$http_referer","HttpRequestUserAgent":"$http_user_agent","Service":"nginx","level":"info","msg":"nginx_request_stop","UpstreamName":"$proxy_upstream_name","AlternativeUpstreamName":"$proxy_alternative_upstream_name","UpstreamResponseTime":"$upstream_response_time","UpstreamStatus":"$upstream_status"}'
  log-format-escape-json: "true"
