//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Portal.Extensions.ExtensionTemplate.Client
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Portal.Extensions.ExtensionTemplate.Client.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string AssetPropertyNames_CloudService_Location
        {
            get
            {
                return ResourceManager.GetString("AssetPropertyNames_CloudService_Location", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        public static string AssetPropertyNames_Plans_ResourceGroup
        {
            get
            {
                return ResourceManager.GetString("AssetPropertyNames_Resource_ResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to my resources.
        /// </summary>
        public static string CodespacesNames_Plans_lowerPlural
        {
            get
            {
                return ResourceManager.GetString("CodespacesNames_Plans_lowerPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to my resource.
        /// </summary>
        public static string CodespacesNames_Plans_lowerSingular
        {
            get
            {
                return ResourceManager.GetString("CodespacesNames_Plans_lowerSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Resources.
        /// </summary>
        public static string CodespacesNames_Plans_plural
        {
            get
            {
                return ResourceManager.GetString("CodespacesNames_Plans_plural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Resource.
        /// </summary>
        public static string CodespacesNames_Plans_singular
        {
            get
            {
                return ResourceManager.GetString("CodespacesNames_Plans_singular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the name.
        /// </summary>
        public static string EnterTheName
        {
            get
            {
                return ResourceManager.GetString("EnterTheName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ExtensionTemplate.
        /// </summary>
        public static string ExtensionName
        {
            get
            {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://msdn.microsoft.com.
        /// </summary>
        public static string htmlSiteMSDNAddress
        {
            get
            {
                return ResourceManager.GetString("htmlSiteMSDNAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link Property Label.
        /// </summary>
        public static string LinkPropertyLabel
        {
            get
            {
                return ResourceManager.GetString("LinkPropertyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText
        {
            get
            {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to www.microsoft.com.
        /// </summary>
        public static string MicrosoftUri
        {
            get
            {
                return ResourceManager.GetString("MicrosoftUri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string MonitoringLensTitle
        {
            get
            {
                return ResourceManager.GetString("MonitoringLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fix the errors on this page before continuing..
        /// </summary>
        public static string pleaseFixErrors
        {
            get
            {
                return ResourceManager.GetString("pleaseFixErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesBladeTitle
        {
            get
            {
                return ResourceManager.GetString("PropertiesBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property label.
        /// </summary>
        public static string PropertyLabel
        {
            get
            {
                return ResourceManager.GetString("PropertyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property value.
        /// </summary>
        public static string PropertyValue
        {
            get
            {
                return ResourceManager.GetString("PropertyValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property with hyperlink.
        /// </summary>
        public static string PropertyWithHyperlink
        {
            get
            {
                return ResourceManager.GetString("PropertyWithHyperlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start Blade Subtitle.
        /// </summary>
        public static string QuickStartBladeSubtitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartBladeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start Blade Title.
        /// </summary>
        public static string QuickStartBladeTitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start Description.
        /// </summary>
        public static string QuickStartDescription
        {
            get
            {
                return ResourceManager.GetString("QuickStartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This section has an Icon and will open a new browser tab on click. These two factors are mutually exclusive as the first depends on if an iconUri is set and the second because section.selectable was populated. This description text is multiline..
        /// </summary>
        public static string QuickStartInfoListDesc1
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListDesc1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDL provides openBlades and links[] of the InfoListBladeLinkContract type will be opened in blades. The tile supports both blade links and hyperlinks in the same section. Numbers are used when iconUri is not set..
        /// </summary>
        public static string QuickStartInfoListDesc2
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListDesc2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon &amp; Selectable.
        /// </summary>
        public static string QuickStartInfoListTitle1
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Section that opens blade.
        /// </summary>
        public static string QuickStartInfoListTitle2
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListTitle2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartShortTitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartTitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for Create Codespace Subtitle.
        /// </summary>
        public static string CreateCodespaceBladeSubtitle
        {
            get
            {
                return ResourceManager.GetString("CreateCodespaceBladeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for Create Codespace Title.
        /// </summary>
        public static string CreateCodespaceBladeTitle
        {
            get
            {
                return ResourceManager.GetString("CreateCodespaceBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Codespaces.
        /// </summary>
        public static string CodespacesBladeSubtitle
        {
            get
            {
                return ResourceManager.GetString("CodespacesBladeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Codespaces.
        /// </summary>
        public static string CodespacesBladeTitle
        {
            get
            {
                return ResourceManager.GetString("CodespacesBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ResourceLocationColumn
        {
            get
            {
                return ResourceManager.GetString("ResourceLocationColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        public static string ResourceName
        {
            get
            {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ResourceNameColumn
        {
            get
            {
                return ResourceManager.GetString("ResourceNameColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The resource name is required.
        /// </summary>
        public static string ResourceNameRequired
        {
            get
            {
                return ResourceManager.GetString("ResourceNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Subtitle.
        /// </summary>
        public static string ResourceOverviewBladeSubtitle
        {
            get
            {
                return ResourceManager.GetString("ResourceOverviewBladeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Title.
        /// </summary>
        public static string ResourceOverviewBladeTitle
        {
            get
            {
                return ResourceManager.GetString("ResourceOverviewBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource part subtitle.
        /// </summary>
        public static string ResourcePartSubtitle
        {
            get
            {
                return ResourceManager.GetString("ResourcePartSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource part title.
        /// </summary>
        public static string ResourcePartTitle
        {
            get
            {
                return ResourceManager.GetString("ResourcePartTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string SelectLocation
        {
            get
            {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a resource group.
        /// </summary>
        public static string SelectResourceGroup
        {
            get
            {
                return ResourceManager.GetString("SelectResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a subscription.
        /// </summary>
        public static string SelectSubscription
        {
            get
            {
                return ResourceManager.GetString("SelectSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription
        {
            get
            {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription Id.
        /// </summary>
        public static string SubscriptionId
        {
            get
            {
                return ResourceManager.GetString("SubscriptionId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text Property Label.
        /// </summary>
        public static string TextPropertyLabel
        {
            get
            {
                return ResourceManager.GetString("TextPropertyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validating....
        /// </summary>
        public static string Validating
        {
            get
            {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
    }
}
