# pipeline vsclk-online-dev-ci-release.yml

variables:
  - template: variables/vsclk-cluster-online-dev-ci-variables.yml

name: ${{ variables.nameFormat }}

stages:
  - template: templates/deploy-cluster-stages.yml
    parameters:
      pool: ${{ variables.linuxPool }}
      serviceConnector: ${{ variables.serviceConnector }}
      azureContainerRegistry: ${{ variables.azureContainerRegistry }}
      serviceSubscription: ${{ variables.serviceSubscription }}
      servicePrefix: ${{ variables.servicePrefix }}
      serviceName: ${{ variables.serviceName }}
      serviceEnv: ${{ variables.serviceEnv }}
      serviceInstance: ${{ variables.serviceInstance }}
      serviceLocation: ${{ variables.serviceLocation }}
      dnsName: ${{ variables.dnsName }}
      teamGroupId: ${{ variables.teamGroupId }}
      sslCertKeyvaultName: ${{ variables.sslCertKeyvaultName }}
      sslCertSecrets: ${{ variables.sslCertSecrets }}
      clusterVersion: ${{ variables.clusterVersion }}
      clusterNodeCount: ${{ variables.clusterNodeCount }}
      signlrEnabled: ${{ variables.signlrEnabled }}
      signlrCapacity: ${{ variables.signlrCapacity }}
      signlrCapacitySecondary: ${{ variables.signlrCapacitySecondary }}
      flags: ${{ variables.deployClusterAdditionalFlags }}
      helmVersion: ${{ variables.helmVersion }}
      kubectlVersion: ${{ variables.kubectlVersion }}
      regions:
        - usw2
        - euw
      portForwardingEnabled: ${{ variables.portForwardingEnabled }}

trigger:
  batch: false
  branches:
    include:
      - "master"
  paths:
    include:
      - "src/*"
