kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-default-psp-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - custom-default-psp
