# Default values for the vsclk-enverg-webapi chart

pods:
  replicaCount: 1
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath:
  readinessProbePath:
  targetCpuUtilizationPercentage: 60

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.envreg.webapi
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: envreg
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
  path: /api/environment/?(.*)

appSettings:
- ASPNETCORE_ENVIRONMENT
- ENVREG_AppSettings__AuthJwtAudiences
- ENVREG_AppSettings__AuthJwtAuthority
- ENVREG_AppSettings__VsClkEnvRegDbHost
- ENVREG_AppSettings__VsClkEnvRegDbKey
- ENVREG_AppSettings__VsClkEnvRegPreferredLocation
- ENVREG_AppSettings__VsClkEnvRegDbId
- ENVREG_AppSettings__KeyVaultName
- ENVREG_AppSettings__VsClkRedisConnectionString
- ENVREG_AppSettings__ComputeServiceUrl

azure-secrets:
  # vsclk-core-dev
  subscriptionId-dev: "86642df6-843e-4610-a956-fdd497102261"
  # vsclk-core-ppe
  subscriptionId-ppe: "a3c9bfe3-6696-4b72-a51a-48d3f6e69a24"
  # vsclk-core-prod
  subscriptionId-prod: "979523fb-a19c-4bb0-a8ee-cef29597b0a4"
  keyVaultName-dev: vsclk-online-dev-kv
  keyVaultName-ppe: vsclk-online-ppe-kv
  keyVaultName-prod: vsclk-online-prod-kv

authentication:
  authority: https://login.windows.net/common
  # Note that 9db1d849-f699-4cfb-8160-64bed3335c72 is the DEV appid
  # the others are temporary, client appids
  audiences: "https://management.core.windows.net/,9db1d849-f699-4cfb-8160-64bed3335c72,aebc6443-996d-45c2-90f0-388ff96faa56,872cd9fa-d31f-45e0-9eab-6e460a02d1f1"

config:
  databaseId: environment-registration
  dbPreferredLocation: eastus
  computeServiceUrl: http://computeprovisioning
