apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend-web-api.fullname" . }}-settings
  labels:
{{ include "frontend-web-api.labels" . | indent 4 }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspNetEnv | b64enc }}
  RUNNING_IN_AZURE: {{ "true" | b64enc }}
  APPSECRETS__APPSERVICEPRINCIPALCLIENTSECRET: ![kvb64=app-sp-password]!
  OVERRIDE_APPSETTINGS_JSON: {{ .Values.config.overrideAppSettingsJson | b64enc }}
