{{- if .Values.image.pullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.image.pullSecret.name }}"
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ template "dockercfg" . }}
{{- end -}}