{{- if eq .Values.mdm.useSecretFile true }}
apiVersion: v1
kind: Secret
metadata:
  name: mdm-cert
type: Opaque
data:
  cert.pem: {{ .Files.Get .Values.mdm.certFile | b64enc | quote }}
  key.pem: {{ .Files.Get .Values.mdm.keyFile | b64enc | quote }}
{{- end }}