apiVersion: v1
kind: Service
metadata:
  name: {{ template "prom-mdm-converter.fullname" . }}
  labels:
    app: {{ template "prom-mdm-converter.name" . }}
    chart: {{ template "prom-mdm-converter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.internalPort }}
      protocol: TCP
      name: prometheusreceiver
  selector:
    app: {{ template "prom-mdm-converter.name" . }}
    release: {{ .Release.Name }}
