# pipeline docker-compose-release.yml

name: docker-compose-{{{env}}}-release

stages:
- stage: docker_compose_{{{env}}}
  displayName: docker_compose_{{{env}}}
  dependsOn: []
  variables:
    displayName: docker_compose_{{{env}}}
    pool: Hosted Ubuntu 1604
    targetServiceConnector: {{{basePlaneName}}}-sp
    targetContainerRegistry: {{{prefix}}}{{{component}}}{{{env}}}{{{plane}}}acr.azurecr.io
    linuxGenevaServiceConnector: vsclk-linuxgeneva-acr
    linuxGenevaContainerRegistry: linuxgeneva-microsoft.azurecr.io
    kubernetesSharedServiceConnector: KubernetesSharedACR
    kubernetesSharedContainerRegistry: kubernetesshared.azurecr.io

  jobs:
  - job: docker_compose_{{{env}}}_job
    pool:
      name: ${{ variables.pool }}
    displayName: ${{ variables.displayName }} on ${{ variables.pool }}

    steps:

    - checkout: self
      clean: false
      fetchDepth: 1
      lfs: true
      path: vsclk_core

    - task: Bash@3
      displayName: Echo variables
      inputs:
        targetType: inline
        script: |
          echo "targetServiceConnector: ${{ variables.targetServiceConnector }}"
          echo "targetContainerRegistry: ${{ variables.targetContainerRegistry }}"
          echo "linuxGenevaServiceConnector: ${{ variables.linuxGenevaServiceConnector}}"
          echo "linuxGenevaContainerRegistry: ${{ variables.linuxGenevaContainerRegistry }}"
          echo "kubernetesSharedServiceConnector: ${{ variables.kubernetesSharedServiceConnector }}"
          echo "kubernetesSharedContainerRegistry: ${{ variables.kubernetesSharedContainerRegistry }}"

    # public images
    - template: docker-compose-steps.yaml
      parameters:
        name: public registires
        dockerComposeFile: '$(System.DefaultWorkingDirectory)/ops/Components.generated/Core/{{{basePlaneFileName}}}/docker-compose/public/docker-compose.yaml'
        sourceServiceConnector:
        sourceContainerRegistry:
        targetServiceConnector: ${{ variables.targetServiceConnector }}
        targetContainerRegistry: ${{ variables.targetContainerRegistry }}

    # linuxgeneva
    - template: docker-compose-steps.yaml
      parameters:
        name: linuxgeneva
        dockerComposeFile: '$(System.DefaultWorkingDirectory)/ops/Components.generated/Core/{{{basePlaneFileName}}}/docker-compose/linuxgeneva/docker-compose.yaml'
        sourceServiceConnector: ${{ variables.linuxGenevaServiceConnector }}
        sourceContainerRegistry: ${{ variables.linuxGenevaContainerRegistry }}
        targetServiceConnector: ${{ variables.targetServiceConnector }}
        targetContainerRegistry: ${{ variables.targetContainerRegistry }}

    # kubernetesshared
    - template: docker-compose-steps.yaml
      parameters:
        name: kubernetesshared
        dockerComposeFile: '$(System.DefaultWorkingDirectory)/ops/Components.generated/Core/{{{basePlaneFileName}}}/docker-compose/kubernetesshared/docker-compose.yaml'
        sourceServiceConnector: ${{ variables.kubernetesSharedServiceConnector }}
        sourceContainerRegistry: ${{ variables.kubernetesSharedContainerRegistry }}
        targetServiceConnector: ${{ variables.targetServiceConnector }}
        targetContainerRegistry: ${{ variables.targetContainerRegistry }}

trigger:
  batch: false
  branches:
    include:
      - "staging"
  paths:
    include:
      - "ops/*"
