apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-web-api.fullname" . }}-settings
  labels:
{{ include "backend-web-api.labels" . | indent 4 }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspNetEnv | b64enc }}
  AppSettings__StorageAccountSettings__StorageAccountName: ![kvb64=Config-Storage-AccountName-usw2]!
  AppSettings__StorageAccountSettings__StorageAccountKey: ![kvb64=Config-Storage-AccountKey-usw2]!
