# empty-stage.yml
# TODO: How to declare a stage with no jobs. Azure DevOps gives an error if jobs is empty.

parameters:
  name: ''
  displayName: ''
  dependsOn: []
  pool: ''

stages:
- stage: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - job: ${{ parameters.name }}_Job
    pool:
      name: ${{ parameters.pool }}
    displayName: ${{ parameters.displayName }} on ${{ parameters.pool }}
    steps:
    - checkout: none
