apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service.fullname" . }}-settings
  {{ template "labels" . }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspNetEnv | b64enc }}
  PORTAL_AppSettings__AesKey: '![kvb64=Config-AesKey]!'
  PORTAL_AppSettings__AesIV: '![kvb64=Config-AesIV]!'
  PORTAL_AppSettings__Domain: {{ .Values.config.clusterDefaultHost | b64enc }}
  PORTAL_AppSettings__MicrosoftAppClientId: {{ "ce5aa96e-1717-4055-a2b5-cfe4aebbf36d" | b64enc }}
  PORTAL_AppSettings__MicrosoftAppClientSecret: '![kvb64=Config-MicrosoftAppClientSecret]!'
  PORTAL_AppSettings__AuthRedirectUrl: {{ .Values.config.authRedirectUrl | b64enc }}
  # TODO: this is the global key-vault
  PORTAL_AppSettings__KeyVaultName: {{ .Values.config.keyVaultName | b64enc }}
  # TODO: the redis cache is per instance, not global, but pulled from global KV
  PORTAL_AppSettings__VsClkRedisConnectionString: '![kvb64=Config-RedisConnectionString]!'
  # TODO: the signalr is per stamp, not global, but pulled from global KV
  PORTAL_AppSettings__VsClkSignalRConnectionString: '![kvb64=Config-SignalRConnectionString]!'
  PORTAL_AppSettings__PortalEndpoint: {{ .Values.config.portalEndpoint | b64enc }}
  PORTAL_AppSettings__EnvironmentRegistrationEndpoint: {{ .Values.config.environmentRegistrationEndpoint | b64enc }}
  PORTAL_AppSettings__ApiEndpoint: {{ .Values.config.apiEndpoint | b64enc }}
  PORTAL_AppSettings__LiveShareEndpoint: {{ .Values.config.liveShareEndpoint | b64enc }}
  PORTAL_AppSettings__LiveShareWebExtensionEndpoint: {{ .Values.config.liveShareWebExtensionEndpoint | b64enc }}
  PORTAL_AppSettings__RichNavWebExtensionEndpoint: {{ .Values.config.richNavWebExtensionEndpoint | b64enc }}
  PORTAL_AppSettings__GitHubAppClientId: {{ .Values.config.githubClientId | b64enc }}
  PORTAL_AppSettings__GitHubAppClientSecret: '![kvb64=Config-GitHubAppClientSecret]!'
  PORTAL_AppSettings__GitHubNativeAppClientId: {{ .Values.config.githubNativeClientId | b64enc }}
  PORTAL_AppSettings__GitHubNativeAppClientSecret: '![kvb64=Config-GitHubNativeAppClientSecret]!'
  PORTAL_AppSettings__KeyVaultReaderServicePrincipalClientId: '![kvb64=app-sp-appid]!'
  PORTAL_AppSettings__KeyVaultReaderServicePrincipalClientSecret: '![kvb64=app-sp-password]!'
  PORTAL_AppSettings__AzDevAppClientId: {{ .Values.config.azDevClientId | b64enc }}
  PORTAL_AppSettings__AzDevAppClientSecret: '![kvb64=Config-AzDevAppClientSecret]!'
  PORTAL_AppSettings__VsSaaSTokenIssuer: {{ .Values.config.vsSaaSTokenIssuer | b64enc }}
  PORTAL_AppSettings__VsSaaSTokenCertsEndpoint: {{ .Values.config.vsSaaSTokenCertsEndpoint | b64enc }}
  PORTAL_AppSettings__VsSaaSCertificateSecretName: {{ .Values.config.vsSaaSCertificateSecretName | b64enc }}
  PORTAL_AppSettings__PortForwardingDomainTemplate: {{ .Values.config.portForwardingDomainTemplate | b64enc }}
  PORTAL_AppSettings__PortForwardingServiceEnabled: {{ .Values.config.portForwardingServiceEnabled | b64enc }}
  PORTAL_AppSettings__GitHubPortForwardingDomainTemplate: {{ .Values.config.gitHubPortForwardingDomainTemplate | b64enc }}
  PORTAL_AppSettings__PortForwardingEnableEnvironmentEndpoints: {{ .Values.config.portForwardingEnableEnvironmentEndpoints | b64enc }}
  PORTAL_AppSettings__GitHubPortForwardingEnableEnvironmentEndpoints: {{ .Values.config.gitHubportForwardingEnableEnvironmentEndpoints | b64enc }}