# Default values for char vsclk-portal-website.

pods:
  replicaCount: 1
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath:
  readinessProbePath:
  targetCpuUtilizationPercentage: 60

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.portal.website
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: portal
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations: {}
  path: /

appSettings:
- ASPNETCORE_ENVIRONMENT
- PORTAL_AppSettings__KeyVaultName
- PORTAL_AppSettings__AuthRedirectUrl
- PORTAL_AppSettings__VsClkRedisConnectionString
- PORTAL_AppSettings__MicrosoftAppClientId
- PORTAL_AppSettings__MicrosoftAppClientSecret

azure-secrets:
  # vsclk-core-dev
  subscriptionId-dev: "86642df6-843e-4610-a956-fdd497102261"
  # vsclk-core-ppe
  subscriptionId-ppe: "a3c9bfe3-6696-4b72-a51a-48d3f6e69a24"
  # vsclk-core-prod
  subscriptionId-prod: "979523fb-a19c-4bb0-a8ee-cef29597b0a4"
  keyVaultName-dev: vsclk-online-dev-kv
  keyVaultName-ppe: vsclk-online-ppe-kv
  keyVaultName-prod: vsclk-online-prod-kv
  