# Default values for char vsclk-portal-website.

pods:
  replicaCount: 3
  maxReplicaCount: 10
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath: /
  readinessProbePath:
  targetCpuUtilizationPercentage: 60

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.portal.website
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: portal
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations: {}
  path: /

pfingress:
  enabled: true
  annotations:
    # Auth applies to both Portal and PFS as nginx config for the same host gets merged    
    nginx.ingress.kubernetes.io/auth-url: "http://portal-vsclk-portal-website.default.svc.cluster.local/auth"
    nginx.ingress.kubernetes.io/auth-signin: "/signin"
    nginx.ingress.kubernetes.io/auth-cache-key: $remote_addr$http_x_vsonline_authentication$cookie_vso_pf
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 1m
    nginx.ingress.kubernetes.io/auth-response-headers: X-VSOnline-Forwarding-Token,X-VSOnline-Forwarding-Port,X-VSOnline-Forwarding-WorkspaceId
    # Server configurations from canary ingresses don't have effect, the annotations need to be applied to non-canary ingress rules.    
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_intercept_errors on;
      error_page 302 = @handle_error;
    nginx.ingress.kubernetes.io/server-snippet: |
      location @handle_error {
        if ($upstream_http_location ~* "^https?:\/\/pf-(?<pf_session>[0-9a-f]{36}-\d{2,5})\.(?<subdomain>[^\/]+)(?<path>\/.*)$") {
          proxy_pass 'http://pf-$pf_session.$subdomain';
        }
      }
      location /authenticate-port-forwarder {
        proxy_pass_request_body on;
        proxy_pass 'http://portal-vsclk-portal-website.default.svc.cluster.local';
      }
      location /logout-port-forwarder {
        proxy_pass 'http://portal-vsclk-portal-website.default.svc.cluster.local';
      }
      location /signin {
        proxy_pass 'http://portal-vsclk-portal-website.default.svc.cluster.local';
      }
      location /favicon.ico {
        proxy_pass 'http://portal-vsclk-portal-website.default.svc.cluster.local';
      }
      location /site.css {
        proxy_pass 'http://portal-vsclk-portal-website.default.svc.cluster.local';
      }
      location /spinner-dark.svg {
        proxy_pass 'http://portal-vsclk-portal-website.default.svc.cluster.local';
      }
      location /ms-logo.svg {
        proxy_pass 'http://portal-vsclk-portal-website.default.svc.cluster.local';
      }
  path: /

appSettings:
  - ASPNETCORE_ENVIRONMENT
  - PORTAL_AppSettings__AesKey
  - PORTAL_AppSettings__AesIV
  - PORTAL_AppSettings__Domain
  - PORTAL_AppSettings__KeyVaultName
  - PORTAL_AppSettings__AuthRedirectUrl
  - PORTAL_AppSettings__VsClkRedisConnectionString
  - PORTAL_AppSettings__MicrosoftAppClientId
  - PORTAL_AppSettings__MicrosoftAppClientSecret
  - PORTAL_AppSettings__PortalEndpoint
  - PORTAL_AppSettings__EnvironmentRegistrationEndpoint
  - PORTAL_AppSettings__ApiEndpoint
  - PORTAL_AppSettings__LiveShareEndpoint
  - PORTAL_AppSettings__LiveShareWebExtensionEndpoint
  - PORTAL_AppSettings__GitHubAppClientId
  - PORTAL_AppSettings__GitHubAppClientSecret
  - PORTAL_AppSettings__GitHubNativeAppClientId
  - PORTAL_AppSettings__GitHubNativeAppClientSecret
  - PORTAL_AppSettings__KeyVaultReaderServicePrincipalClientId
  - PORTAL_AppSettings__KeyVaultReaderServicePrincipalClientSecret
  - PORTAL_AppSettings__AzDevAppClientId
  - PORTAL_AppSettings__AzDevAppClientSecret
  - PORTAL_AppSettings__VsSaaSTokenIssuer
  - PORTAL_AppSettings__VsSaaSCertificateSecretName
