# Default values for char vsclk-portal-website.

pods:
  replicaCount: 1
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  livenessProbePath:
  readinessProbePath:
  targetCpuUtilizationPercentage: 60

image:
  tag:
  repositoryUrl:
  repositoryName: vsclk.portal.website
  pullPolicy: IfNotPresent
  imagePullSecret:

service:
  name: portal
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations: {}
  path: /

appSettings:
- ASPNETCORE_ENVIRONMENT
- PORTAL_AppSettings__KeyVaultName
- PORTAL_AppSettings__AuthRedirectUrl
- PORTAL_AppSettings__VsClkRedisConnectionString
- PORTAL_AppSettings__MicrosoftAppClientId
- PORTAL_AppSettings__MicrosoftAppClientSecret
