image:
  repositoryUrl: vscscoreprodacr.azurecr.io
  acskeyvaultagentTag: master_28
  genevafluentdtdagentTag: master_148
  genevamdmTag: master_48
  genevamdsdTag: master_309
  genevasecpackinstallTag: master_57

config:
  AzSecPack_AuditMoniker: vsonlineprodaudit
  AzSecPack_DiagnosticsMoniker: vsonlineproddiag
  AzSecPack_EventVersion: 1
  AzSecPack_GCS_Account: VsOnlineProd
  AzSecPack_GCS_cert_name: vsclk-core-prod-monitoring
  AzSecPack_GCS_cert: /secrets/certs/vsclk-core-prod-monitoring
  AzSecPack_GCS_Environment: DiagnosticsProd
  AzSecPack_GCS_key: /secrets/keys/vsclk-core-prod-monitoring
  AzSecPack_Namespace: VsOnlineProd
  AzSecPack_Role: vsonlineprodsecurity
  AzSecPack_SecurityMoniker: vsonlineprodsecurity
  AzSecPack_Tenant: 33e01921-4d64-4f8c-a055-5bdaffd5e33d
  AzSecPack_Timestamp: 2018-05-07T00:00:00Z
  Geneva_Mdm_Account: VsOnlineProd
  KeyVault: https://vscs-core-prod-ops-kv.vault.azure.net/
