trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- pwsh: .\Update-GeneratedFiles.ps1 -FailIfFilesModified -UpdateAppSettings -UpdateComponents
  displayName: Check generated files
  workingDirecotry: $(build.sourcesDirectory)\ops\Scripts
