# Default values for vsclk-backplaneservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appSettings:
- ASPNETCORE_ENVIRONMENT
- RUNNING_IN_AZURE
- AppSettings__Stamp
- AppSettings__ImageTag
- AppSettings__SubscriptionId
- AppSettings__ResourceGroupName
- AppSettings__ResourceGroupInstanceName
- AppSettings__AzureCacheRedisName
- AppSettings__AzureCosmosDbName
- ApplicationServicePrincipal__ClientId
- ApplicationServicePrincipal__TenantId
- ApplicationServicePrincipal__ClientPassword

#define the stamp (this will be overridden by the release definition for each stamp/location)
stamp: usw2

pods:
  minReplicaCount: 1
  maxReplicaCount: 5
  minReadySeconds: 1
  progressDeadlineSeconds: 300
  readinessProbePath: /warmup
  readinessProbeDelaySeconds: 30
  readinessProbeTimeoutSeconds: 60
  readinessProbePeriodSeconds: 45
  targetCpuUtilizationPercentage: 80
  autoscaling: false

image:
  pullPolicy: IfNotPresent
  repositoryUrl:
  repositoryName: vsclk.backplaneservice
  tag:
  imagePullSecret:

service:
  type: ClusterIP
  port: 80
  containerPort: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1700m
    memory: 2800Mi
  requests:
    cpu: 1200m
    memory: 1200Mi

nodeSelector: {}

tolerations: []

affinity: {}
