version: "3"

services:
  vsclk.portal.website:
    image: vsclk.portal.website
    build:
      context: ../../VsClk.Portal.WebSite
      dockerfile: Dockerfile
  vsclk.signalservice:
    image: vsclk.signalservice
    build:
      context: ../../SignalService
      dockerfile: Dockerfile
