apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vsclk-signalservice.fullname" . }}-settings
  {{ template "labels" . }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspNetEnv | b64enc }}
  AppSettings__Stamp: {{ .Values.stamp | b64enc }}
  AppSettings__BaseUri: {{ .Values.baseUri | b64enc }}
  AppSettings__ImageTag: {{ .Values.image.tag | b64enc }}
  AppSettings__AuthenticateProfileServiceUri: {{ .Values.authentication.authenticateProfileServiceUri | b64enc }}
  AppSettings__KeyVaultName: {{ .Values.config.keyVaultName | b64enc }}
  AppSettings__SubscriptionId: {{ .Values.config.subscriptionId | b64enc }}
  AppSettings__ResourceGroupName: {{ .Values.config.resourceGroupName | b64enc }}
  AppSettings__ResourceGroupInstanceName: {{ .Values.config.resourceGroupInstanceName | b64enc }}
  AppSettings__AzureCacheRedisName: {{ .Values.config.cacheRedisName | b64enc }}
  AppSettings__AzureCosmosDbName: {{ .Values.config.cosmosDBName | b64enc }}
  ApplicationServicePrincipal__ClientId: '![kvb64=app-sp-appid]!'
  ApplicationServicePrincipal__TenantId: '![kvb64=app-sp-tenant]!'
  ApplicationServicePrincipal__ClientPassword: '![kvb64=app-sp-password]!'
