apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vsclk-signalservice.fullname" . }}-settings
  {{ template "labels" . }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspNetEnv | b64enc }}
  AppSettings__Stamp: {{ .Values.stamp | b64enc }}
  AppSettings__BaseUri: {{ .Values.baseUri | b64enc }}
  AppSettings__ImageTag: {{ .Values.image.tag | b64enc }}
  AppSettings__AuthenticateProfileServiceUri: {{ .Values.authentication.authenticateProfileServiceUri | b64enc }}
  AppSettings__AzureCosmosDbEndpointUrl: '![kvb64=Config-AzureCosmosDbHost]!'
  AppSettings__AzureCosmosDbAuthKey: '![kvb64=Config-AzureCosmosDbAuthKey]!'

# add this to enable the AzureRedisConnection config
#  AppSettings__AzureRedisConnection: '![kvb64=Config-RedisConnectionString]!'

# pull the proper value based on the region stamp from .Values
{{- if eq .Values.stamp "use" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-use]!'
  Azure__SignalR__ConnectionString__Secondary: '![kvb64=Config-SignalRConnectionString-use-secondary]!'
{{- else if eq .Values.stamp "usw2" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-usw2]!'
  Azure__SignalR__ConnectionString__Secondary: '![kvb64=Config-SignalRConnectionString-usw2-secondary]!'
{{- else if eq .Values.stamp "euw" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-euw]!'
  Azure__SignalR__ConnectionString__Secondary: '![kvb64=Config-SignalRConnectionString-euw-secondary]!'
{{- else if eq .Values.stamp "asse" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-asse]!'
  Azure__SignalR__ConnectionString__Secondary: '![kvb64=Config-SignalRConnectionString-asse-secondary]!'
{{- end -}}
