apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vsclk-signalservice.fullname" . }}-settings
  {{ template "labels" . }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspNetEnv | b64enc }}
  SIGNALR_AppSettings__AuthenticateMetadataServiceUri: {{ .Values.authentication.authenticateMetadataServiceUri | b64enc }}
  SIGNALR_AppSettings__AzureCosmosDbAuthKey: '![kvb64=Config-AzureCosmosDbAuthKey]!'
  SIGNALR_AppSettings__AzureCosmosDbEndpointUrl: '![kvb64=Config-AzureCosmosDbHost]!'
  SIGNALR_AppSettings__AzureSignalRConnectionString: '![kvb64=Config-SignalRConnectionString]!'
  SIGNALR_AppSettings__BuildVersion: {{ .Values.status.buildVersion | b64enc }}
  SIGNALR_AppSettings__GitCommit: {{ .Values.status.gitCommit | b64enc }}
  AppSettings__AuthenticateMetadataServiceUri: {{ .Values.authentication.authenticateMetadataServiceUri | b64enc }}
  AppSettings__AzureCosmosDbEndpointUrl: '![kvb64=Config-AzureCosmosDbHost]!'
  AppSettings__AzureCosmosDbAuthKey: '![kvb64=Config-AzureCosmosDbAuthKey]!'
  AppSettings__BuildVersion: {{ .Values.status.buildVersion | b64enc }}
  AppSettings__GitCommit: {{ .Values.status.gitCommit | b64enc }}
  AppSettings__UseTelemetryProvider: {{ .Values.enableTelemetrySupport | b64enc }}

# pull the proper value based on the region stamp from .Values
{{- if eq .Values.stamp "use" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-use]!'
{{- else if eq .Values.stamp "usw2" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-usw2]!'
{{- else if eq .Values.stamp "euw" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-euw]!'
{{- else if eq .Values.stamp "asse" -}}
data:
  Azure__SignalR__ConnectionString: '![kvb64=Config-SignalRConnectionString-asse]!'
{{- end -}}
