config:
  AzSecPack_GCS_cert_name: "vsclk-core-ppe-monitoring"
  AzSecPack_GCS_cert: "/secrets/certs/vsclk-core-ppe-monitoring"
  AzSecPack_GCS_key: "/secrets/keys/vsclk-core-ppe-monitoring"
  AzSecPack_GCS_Environment: "DiagnosticsProd"
  AzSecPack_GCS_Account: "VsOnlinePpe"
  AzSecPack_EventVersion: "1"
  AzSecPack_Timestamp: "2018-05-07T00:00:00Z"
  AzSecPack_Namespace: "VsOnlineSignalrPpe"
  AzSecPack_AuditMoniker: "vsonlinesignalrppeaudit"
  AzSecPack_DiagnosticsMoniker: "vsonlinesignalrppediag"
  AzSecPack_SecurityMoniker: "vsonlinesignalrppesecurity"
  AzSecPack_Tenant: "72f988bf-86f1-41af-91ab-2d7cd011db47"
  AzSecPack_Role: "vsonlinesignalrppesecurity"
  KeyVault: "https://vsclk-core-ppe-kv.vault.azure.net/"
  Geneva_Mdm_Account: "VsOnlinePpe"