version: '3'

services:

  # We use alpine + docker in the "docker-image-cleanup-daemonset" chart to clean up unused docker images
  alpine:
    image: alpine-docker:1
    build:
      context: .
      dockerfile: alpine-docker.dockerfile
      args:
      - base_image=docker.io/library/alpine@sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a

  # We use busybox in the "geneva" chart to obtain values from IMDS
  busybox:
    image: busybox:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - base_image=docker.io/library/busybox@sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d

  # See gcr.io/google_containers/defaultbackend:1.4
  # See k8s.gcr.io/defaultbackend:1.4
  k8s_defaultbackend:
    image: k8s-defaultbackend:1.4
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - base_image=k8s.gcr.io/defaultbackend@sha256:865b0c35e6da393b8e80b7e3799f777572399a4cff047eb02a81fa6e7a48ed4b

  # We used kured in the "kured" chart for managing reboot cycle of linux nodes.
  # See https://github.com/weaveworks/kured.
  kured:
    image: kured-modded:1
    build:
      context: .
      dockerfile: kured-modded.dockerfile
      args:
      - base_image=docker.io/weaveworks/kured@sha256:91335d3a1215eb768a440bf2b6779bd4ec2023ff2251f4b7af371f1e5ce65bdb

  # See quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.27.1
  nginx_ingress_controller:
    image: nginx-ingress-controller:0.27.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - base_image=quay.io/kubernetes-ingress-controller/nginx-ingress-controller@sha256:3d93f5ba697f7014e0b639eb5b2abbaa7e20d70a4fd759612c52c1fc5d506612
