image:
  repositoryUrl: vscscoreppeacr.azurecr.io
  acskeyvaultagentTag: master_28
  genevafluentdtdagentTag: master_148
  genevamdmTag: master_48
  genevamdsdTag: master_309
  genevasecpackinstallTag: master_57

config:
  AzSecPack_AuditMoniker: vsonlineppeaudit
  AzSecPack_DiagnosticsMoniker: vsonlineppediag
  AzSecPack_EventVersion: 1
  AzSecPack_GCS_Account: VsOnlinePpe
  AzSecPack_GCS_cert_name: vsclk-core-ppe-monitoring
  AzSecPack_GCS_cert: /secrets/certs/vsclk-core-ppe-monitoring
  AzSecPack_GCS_Environment: DiagnosticsProd
  AzSecPack_GCS_key: /secrets/keys/vsclk-core-ppe-monitoring
  AzSecPack_Namespace: VsOnlinePpe
  AzSecPack_Role: vsonlineppesecurity
  AzSecPack_SecurityMoniker: vsonlineppesecurity
  AzSecPack_Tenant: 33e01921-4d64-4f8c-a055-5bdaffd5e33d
  AzSecPack_Timestamp: 2018-05-07T00:00:00Z
  Geneva_Mdm_Account: VsOnlinePpe
  KeyVault: https://vscs-core-ppe-ops-kv.vault.azure.net/
