# Common override values for charts deployed to vsclk-online-dev-ci

image:
  repositoryUrl: vsclkonlineppe.azurecr.io

ingress:
  hosts:
    - online-ppe.core.vsengsaas.visualstudio.com
    - vsclk-online-ppe-rel-asse-tm.trafficmanager.net
    - vsclk-online-ppe-rel-euw-tm.trafficmanager.net
    - vsclk-online-ppe-rel-tm.trafficmanager.net
    - vsclk-online-ppe-rel-use-tm.trafficmanager.net
    - vsclk-online-ppe-rel-usw2-tm.trafficmanager.net
  tls:
    - hosts:
        - online-ppe.core.vsengsaas.visualstudio.com
      secretName: ssl-cert

authentication:
  audiences: "https://management.core.windows.net/,9db1d849-f699-4cfb-8160-64bed3335c72,aebc6443-996d-45c2-90f0-388ff96faa56,872cd9fa-d31f-45e0-9eab-6e460a02d1f1"

config:
  aspNetEnv: Staging
  authRedirectUrl: https://online-ppe.core.vsengsaas.visualstudio.com
  keyVaultName: vsclk-online-ppe-kv
  clusterDefaultHost: online-ppe.core.vsengsaas.visualstudio.com