# Common override values for charts deployed to vsclk-signlr-prod-rel

image:
  repositoryUrl: vsclksignlrprod.azurecr.io

ingress:
  hosts:
    - signlr-prod.core.vsengsaas.visualstudio.com
    - vsclk-signlr-prod-rel-tm.trafficmanager.net
    - vsclk-signlr-prod-rel-asse-tm.trafficmanager.net
    - vsclk-signlr-prod-rel-euw-tm.trafficmanager.net
    - vsclk-signlr-prod-rel-use-tm.trafficmanager.net
    - vsclk-signlr-prod-rel-usw2-tm.trafficmanager.net
  tls:
    - hosts:
      - signlr-prod.core.vsengsaas.visualstudio.com
      secretName: ssl-cert

config:
  aspNetEnv: Production
  keyVaultName: vsclk-signlr-prod-kv
  clusterDefaultHost: signlr-prod.core.vsengsaas.visualstudio.com
  subscriptionId: "979523fb-a19c-4bb0-a8ee-cef29597b0a4"
  resourceGroupName: vsclk-signlr-prod
  resourceGroupInstanceName: vsclk-signlr-prod-rel
  cacheRedisName: vsclk-signlr-prod-rel-redis
  cosmosDBName: vsclk-signlr-prod-rel-db

