apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service.fullname" . }}-settings
  {{ template "labels" . }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspNetEnv | b64enc }}
  ENVREG_AppSettings__AuthJwtAudiences: {{ .Values.authentication.audiences | b64enc }}
  ENVREG_AppSettings__AuthJwtAuthority: {{ .Values.authentication.authority | b64enc }}
  ENVREG_AppSettings__ComputeServiceUrl: {{ .Values.config.computeServiceUrl | b64enc }}
  ENVREG_AppSettings__VsClkEnvRegDbHost: '![kvb64=Config-AzureCosmosDbHost]!'
  ENVREG_AppSettings__VsClkEnvRegDbKey: '![kvb64=Config-AzureCosmosDbAuthKey]!'
  ENVREG_AppSettings__VsClkEnvRegPreferredLocation: {{ .Values.config.dbPreferredLocation | b64enc }}
  ENVREG_AppSettings__VsClkEnvRegDbId: {{ .Values.config.databaseId | b64enc }}
  # TODO: this is the global key-vault
  ENVREG_AppSettings__KeyVaultName: {{ .Values.config.keyVaultName | b64enc }}
  # TODO: the redis cache is per instance, not global, but pulled from global KV
  ENVREG_AppSettings__VsClkRedisConnectionString: '![kvb64=Config-RedisConnectionString]!'
  # TODO: the signalr is per stamp, not global, but pulled from global KV
  ENVREG_AppSettings__VsClkSignalRConnectionString: '![kvb64=Config-SignalRConnectionString]!'
