version: '3'

services:
  # See https://hub.docker.com/_/microsoft-dotnet-core-aspnet/
  microsoft_dotnet_core_aspnet_2_2_3_alpine_3_9:
    # This image tag will be referenced in other Dockerfile FROM clauses
    image: mcr.microsoft.com/dotnet/core/aspnet:2.2.3-alpine3.9
    build:
      context: .
      dockerfile: Dockerfile
      args:
      # This image is used to pull from an external Docker Registry (MCR) into our "local" repository (ACR).
      - base_image=mcr.microsoft.com/dotnet/core/aspnet:2.2.3-alpine3.9
  vsclk.portal.website:
    image: vsclk.portal.website:latest
    build:
      context: ../VsClk.Portal.WebSite
      dockerfile: Dockerfile
    depends_on:
    - microsoft_dotnet_core_aspnet_2_2_3_alpine_3_9

  vsclk.envreg.webapi:
    image: vsclk.envreg.webapi:latest
    build:
      context: ../VsClk.EnvReg.WebApi
      dockerfile: Dockerfile
    depends_on:
    - microsoft_dotnet_core_aspnet_2_2_3_alpine_3_9
