# Adapted from: https://dev.azure.com/msazure/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/35044/Cleanup-the-unused-images-in-the-agent-nodes?anchor=option-1
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-image-cleanup
  namespace: kube-system
  labels:
    tier: management
    app: docker-image-cleanup
spec:
  selector:
    matchLabels:
      name: docker-image-cleanup
  template:
    metadata:
      labels:
        name: docker-image-cleanup
    spec:
      containers:
        - resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          name: docker-image-cleanup
          image: {{ required "Value image.repositoryUrl not specified" .Values.image.repositoryUrl }}/{{ required "Value image.alpineDockerName not specified" .Values.image.alpineDockerName }}:{{ required "Value image.alpineDockerTag not specified" .Values.image.alpineDockerTag }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              while true; do
                docker system prune --all -f;
                sleep 86400;
              done
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-volume
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock