# Config for frontend
frontend-web-api:
  config:
    aspNetEnv: Staging
    overrideAppSettingsJson: false
  ingress:
    hosts:
      - online-ppe.core.vsengsaas.visualstudio.com
      - westus2-ppe-rel-online.core.vsengsaas.visualstudio.com
      - southeastasia-ppe-rel-online.core.vsengsaas.visualstudio.com
    tls:
      - hosts:
        - online-ppe.core.vsengsaas.visualstudio.com
        - westus2-ppe-rel-online.core.vsengsaas.visualstudio.com
        - southeastasia-ppe-rel-online.core.vsengsaas.visualstudio.com
        secretName: ssl-cert

# Config for backend
backend-web-api:
  config:
    aspNetEnv: Staging
    overrideAppSettingsJson: false

# Config for tokens
tokens-web-api:
  config:
    aspNetEnv: Staging
    overrideAppSettingsJson: false
  ingress:
    hosts:
      - sts-ppe.core.vsengsaas.visualstudio.com
      - westus2-ppe-rel-sts.core.vsengsaas.visualstudio.com
      - southeastasia-ppe-rel-sts.core.vsengsaas.visualstudio.com
    tls:
      - hosts:
        - sts-ppe.core.vsengsaas.visualstudio.com
        - westus2-ppe-rel-sts.core.vsengsaas.visualstudio.com
        - southeastasia-ppe-rel-sts.core.vsengsaas.visualstudio.com
        secretName: ssl-cert
