# Config that applies to all charts
global:
  config:
    aspNetEnv: Development

# Config for frontend
frontend-web-api:    
  validJwtAudiences:
  databaseId:

# Config for backend
backend-web-api:
